services:
  - type: web
    name: journaly-backend
    runtime: python
    env: python
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    plan: free
    branch: main
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*.py"
        - requirements.txt
        - render.yaml
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
      - key: TOGETHER_AI_API_KEY
        sync: false
